# Generated by Django 2.1.4 on 2019-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
