# Generated by Django 2.1.4 on 2018-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatistic',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Курс оплачен'),
        ),
    ]
