# Generated by Django 2.1.4 on 2019-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20190105_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date_start',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='coursestatistic',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Тестирование'),
        ),
    ]
